.\" Manpage for np2m.
.TH NP2M 1 "2022 May 14" "NP2M(1)" "COOL Programmer's Manual"
.SH NAME
np2m - NumPad To Mouse 

.SH SYNOPSIS
np2m [\fI--enable\fR|\fI--disable\fR|\fI--switch\fR|\fI--help\fR]

.SH DESCRIPTION
.B np2m
is a shell script to make your useless numpad into a semi-functional mouse

.SH OPTIONS
.TS
tab (@);
l lxx.
\fB--enable @T{
change numPad to semi-functional mouse
T}

--disable @T{
disable numPad mouse
T}

--switch @T{
switch between numPad and mouse
T}

--help @T{
display help about np2m
T}
.TE

.SH SEE ALSO
.B setxkbmap
(1)

.SH AUTHOR
np2m written by jumps-are-op

Man page written by jumps-are-op

.SH LINKS
1. jumps-are-op
.br
	https://github.com/jumps-are-op
